const histories = [
  {
    prehistory: [
      "Long before the arrival of the Spaniards in the Philippines, large centers of population already thrived in Batangas. Native settlements lined the Pansipit River, a major waterway. The province had been trading with the Chinese since Yuan Dynasty until first phase of Ming Dynasty in the 13th and 15th century. Inhabitants of the province were also trading with Japan and India.",
      "Archeological findings, show that even before the settlement of the Spaniards in the country, the Tagalogs, especially the Batangueños, had a very high level of civilization. This was shown by some jewelry, made from a chambered nautilus’ shell, where some tiny holes were drilled by some tube. The way it was drilled shows that early Batangueños had an idea of what is beautiful.",
      "Later, the pre-historic Batangueños was influenced by India as shown in some ancient potteries. In fact, a Buddhist image was reproduced in mould on a clay medallion in bas-relief from the Municipality of Calatagan. According to experts, the image in the pot strongly resembles the iconographic portrayal of Buddha in Siam, India and Nepal. The pot shows Buddha Amithaba in the tribhanga pose inside an oval nimbus. Scholars also noted that there is a strong Mahayanic orientation in the image, since the Boddhisattva Avalokitesvara was also depicted.",
      "One of the major archeological finds was in January 1941, where 2 crude stone figures were found in Palapat in the Municipality of Calatagan. They were later donated to the National Museum. Unfortunately, one of them was destroyed during World War II.",
      "Eighteen years later, a grave was excavated in the nearby Punta Buaya. Once again, it showed that early Batangueños have an appreciation of art, since pieces of brain coral were carved behind the heads of the 12 remains that were found. The site was named ‘Likha’ (meaning ‘Create’). The remains were accompanied by furniture that could be traced as early as the 14th century. Potteries, as well as bracelets, stoneware and metal objects were also found in the area, suggesting that the people who lived there had an extensive contact with people from as far as Chin",
      "The presence of believed also suggested that prehistoric Batangaueños believed in the idea of life-after-death, since someone might need a plate where he would eat or chalices where he could drink. This also related the Batangueños to its neighbors in Asia, where it was a custom to bury some furniture with the dead.",
      "Like the nearby tribes, the Batangan or the early Batanueños were non-aggressive people. Partly because most of the tribes in the immediate environs are related to them by blood. However, when there is no choice but to defend your life, Batangans would use the bakyang (bows and arrows), the bangkaw (spears) and the suwan (bolo).",
      "Another proof of civilization from the Batangans was the presence of religion. Though it was highly superstitious, such as the use of amulet (talisman), it showed that these people believed in the presence of higher beings and other things unseen. Thus, there is a strong connection between the Batangans and nature.",
      "Although it is widely accepted that the term Tagalog came from the word ‘Taga-Ilog’ o river Dwellers, (referring to the Pasig River), Wang The-Ming pointed out in his writings that Batangas was the real centre of the Tagalog Tribe, which he then identified as Ma-yi. According to this Chinese Annals,Ma-yi had its centre in the Province and extends to as far as Cavite, Laguna, Rizal, Quezon, Bataan, Bulacan, Mindoro, Marinduque, Nueva Ecija, Some parts of Zambales and Tarlac. However, many historians interchangeably use the term Tagalog and Batangueño.",
      "Henry Otley Beyer, an American archaeologist, also showed in his studies that the early Batangueños have a special affinity with the precious stone known as the jade. In fact, the named the Late Paleolithic Period of the Philippines as the Batangas Period in recognition of the multitude of jade found in the excavated caves in the province. Beyer identified that the jade-cult reached the Province as early as 800 BC and lasted until 200 BC.",
    ],
    spanish: [
      "In 1570, Spanish generals Martin de Goiti and Juan de Salcedo explored the coast of Batangas on their way to Manila and came upon a Malay settlement at the mouth of Pansipit River. In 1572, the town of Taal was founded and its convent and stone church were constructed later. Officially, the Province of Bonbon was founded by Spain in 1578, through Fr. Estaban Ortiz and Fr. Juan de Porras. It was so named after the name that was given to it by the Muslim natives who inhabited the area.",
      "In 1581, the Spanish government abolished the Bonbon Province and created a new province which came to be known as Balayan Province. The new province was composed of the present provinces of Batangas, Mindoro, Marinduque, southeast Laguna and Camarines. After the devastating eruption of Taal Volcano in 1754, the old town of Taal, present day San Nicolas, was buried. The capital was eventually transferred to Batangas (now a city) in fear of further eruptions where it has remained to date.",
      "The history of Batangas as a province can never be separated from the history of the Christianization of the Islands. In the same years that de Goiti and Salcedo visited the province, the Franciscan missionaries came to Taal. The place later became the first settlement of the Spaniards in Batangas and one of the earliest in the Philippines. In 1572 the Augustinians founded Taal in the place of Wawa, now San Nicolas, and from there began preaching in Balayan and in all the big settlements around the lake of Bombon (Taal). Indeed, the Augustinians did a very good job. Not only did they make Batangas the second most important religious centre of the Archipelago, they did it in a mere 10-year period. In fact, up to now, Batangas remains to be one of the most ‘Christianised’ and even the most ‘Catholic’ Province in the Philippines.",
      "The first missionaries in the diocese were the Augustinians, and they remained until the revolution against Spain. Among the first missionaries were eminent men like Alfonso de Albuquerque, Diego Espinas, Juan de Montojo and others.The first centers of faith were established in Taal, then in Balayan, Bauan, Lipa, Sala, Tanauan, all around the lake of Bombon (Taal).",
      "The first missionaries were the Augustinians. And during the first ten years, the whole region around the lake of Bombon was completely Christianized. It was done through the preaching of men who had learned the first rudiments of the language of the people. At the same time they started writing manuals of devotion in Tagalog,such as novenas. What is more, they wrote the first Tagalog grammar that served other missionaries who came.",
      "The year of foundation of important parishes follows: 1572 the Taal parish was founded by the Augustinians; 1581 the Batangas parish under Fray Diego Mexica; 1596 Bauan parish administered by the Augustinian missionaries; 1605 Lipa parish under the Augustinian administration;1774 Balayan parish was founded; 1852 Nasugbu parish; and 1868 Lemery Parish. Nasugbu became a very important centre of trade during the Spanish occupation of the country. So important was this town that the first recorded battle between two European Forces in Asia was in Fortune Island, Nasugbu, Batangas. In the late part of the 20th Century, the inhabitants of Fortune Island discovered a sunken galleon that contained materials sold in the Manila-Acapulco Galleon Trade. Today, the Galleon stands majestically in the islands as a reminder of the grandeur of Batangan Past.",
      "Batangas was also among the first of the eight Philippine provinces to revolt against Spain and also one of the provinces placed under Martial Law by Spanish Governor General Ramon Blanco on August 30, 1896. This event was given distinction when Marcela Agoncillo, also a native of the province, made the Philippine Flag. Indeed, the official Philippine flag has a sun with eight rays to represent these eight provinces.",
      "Another notable hero from this era is ApolinarioMabini, also known as the sublime paralytic and “Brains of the Revolution”.",
    ],
    american: [
      "The struggles of the Batangueños did not end when the Spaniards left the Philippines. Batangas was also in the watch-list of the Americans when they occupied the Islands.",
      "When the Americans forbade the Philippine flag from being flown anywhere in the country, Batangas was one of the places where the revolutionaries chose to propagate their propaganda. Many, especially the revolutionary artists chose Batangas as the place to perform their plays. In an incident recorded by Amelia Bonifacio in her diary, the performance of Tanikalang Ginto in the province led not only to the arrest of the company but all of the audience. Later, the play was banned from being shown anywhere in the country.",
      "General Miguel Malvar is recognized as the last Filipino general to surrender to the United States in the Philippine-American War.Raph",
    ],
    japanese: [
      "After the attack in Pearl Harbor on December 7, 1941, the Japanese switched their planes to attacking the Philippines, launching major air raids throughout the country. The bombings resulted into the destruction of the Batangas Airport located in Batangas City, of which nothing remains today. Batangas was also a scene of heavy fighting between the Philippine Army Air Corps and the Japanese A6M Zero Fighter Planes. ",
      "The most notable air combat battle took place at height of 3,700 metres (12,000 ft) on December 12, 1941 when 6 Filipino fighters led by Capt. JesúsVillamor engaged the numerically superior enemy of 54 Japanese bombers and fighter escorts which raided the Batangas Airfield. Thus, Capt. JesúsVillamor won the battle, suffering only one casualty, Lt. César Basa whose plane was shot down by seven intercepting enemy fighters which eventually died when he was strafed by machine gun’s fire came from the A6M Zeroes.",
      "When Gen. Douglas MacArthur ordered the overall retreat of the American-Filipino Forces to Bataan in 1942, the province was ultimately abandoned and later came under direct Japanese occupation. During this time, the Imperial Japanese Army committed many crimes against civilians including the massacre of 328 people in Bauan, 320 in Taal, 300 in Cuenca, 107 in San Jose and 39 in Lucero.",
    ],
    postAmerican: [
      "After Douglas MacArthur made his famous landing in the Island of Leyte, he came next to the town of Nasugbu to mark the liberation of Luzon. This historic landing is remembered by the people of Batangas every last day of January, a holiday for the Nasugbugueños. And if Leyte is proud of the bronze statues of McArthur, Batangas can is also proud of their own version of that.",
      "After the Philippines was freed from America, the Batangueños once again entered the picture. Statesmen from Batangas became famous in the government. These include the legislators Felipe Agoncillo, Galicano Apacible (who later became the Secretary of Agriculture), Ramon Diokno, Apolinario R. Apacible, Expedito Leviste, Gregorio Katigbak, Teodoro Kalaw, Claro M. Recto, and Jose Laurel.",
      "Most of these legislators became well known not only in the country but also in the world as many of them held executive offices afterwards. some of them were even sent as Philippine Envoys to other countries.",
      "It is also notable that when Quezon left the Philippines during the Japanese Occupation, the Japanese government in the Philippines chose the Batangueño Jose Laurel, Sr. to the de jure President of the Puppet Republic.",
    ],
    recent: [
      "The 1986 People Power Revolution in EDSA marked another time where Batangueños enter the picture. When Corazon Aquino was inaugurated as president by the bloodless revolution, the Batangueño Salvador Laurel is no less than her Vice-President.",
      "She also appointed Renato de Villa as the Chief of Constabulary and Director-General of the Integrated National Police, and later the Chief of Staff of the Armed Forces of the Philippines. It was under his leadership that the Military remained loyal to Aquino despite the many coup d’etat attempts of Gregorio Honasan. He was also one of the influences behind the Second People Power in 2001.",
      "During the Presidency of Joseph Estrada, he also chose four Batangueños to be his closest advisers. The group was composed of Domingo Panganiban (Department of Agriculture), Benjamin Diokno (Department of Budget and Management), Dong Apacible (Legislative Liaison), Tony “Lepili” Leviste (Board of Investments Governor), and PedFaytaren (Economic Intelligence Chief). This is not to mention Dennis Hernandez, special assistant to Alfredo Lim of theDepartment of Interior and Local Government. During the Estrada Impeachment trial, Hernando Perez, a known lawyer from Batangas City served as private prosecutor.",
      "The Second People Power in 2001 also became an important event for the Batangueños. After Joseph Estrada was thrown off from power, Gloria Macapagal-Arroyo replaced him and chose De Villa as her executive Secretary. He was replaced by Eduardo Ermita, another Batangueño, whom she first appointed as Secretary of the Department National Defence. Three other Batangueños were in the Original the Arroyo Cabinet namely, Noel Cabrera from the Office of the Press Secretary, Renato Corona who was the Presidential Spokesman then later became a Supreme Court Justice, and Hernando Perez who was the Secretary of the Department of Justice.",
      "Leandro Mendoza, who was also chief of the Philippine National Police, was appointed Secretary of the Department of Transportation and Communication upon his retirement, while Lauro Baja, former Undersecretary of the Department of Foreign Affairs was appointed the Philippine Envoy to the United Nations.",
      "Since June 29, 2010, President-elect Aquino, at that time, appoint Br. Armin Luistro FSC as the Secretary of the Department of Education."
    ],
  },
];
export default histories;
